# Generated by Django 5.1.5 on 2025-02-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('betlari_soni', models.IntegerField()),
                ('yili', models.DateField()),
                ('muallifi', models.CharField(max_length=150)),
                ('janr', models.CharField(max_length=150)),
                ('haqida', models.TextField()),
                ('rasmi', models.ImageField(upload_to='kitob_rasmlari/')),
            ],
        ),
    ]
